package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'DeployToLocalMachine'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("DeployToLocalMachine")
    name = "deploy to local machine"

    enablePersonalBuilds = false
    type = BuildTypeSettings.Type.DEPLOYMENT
    maxRunningBuilds = 1

    steps {
        powerShell {
            name = "deployment logic"
            scriptMode = script {
                content = "echo 'Deploy to local machine'"
            }
        }
    }

    dependencies {
        snapshot(RelativeId("Build")) {
            onDependencyFailure = FailureAction.CANCEL
            onDependencyCancel = FailureAction.CANCEL
        }
    }
}))

